baseurl = "http://meetupapp.io/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true

[params]
  title = "meetup app"
  subtitle    = "Following the trend"
  copyright   = "© 2019"

  cover       = "img/cover.png"
#  cover       = "img/blog-cover.jpg"
  description = "エンジニアのための勉強会"
  metaDescription = ""
  googleAnalytics = "UA-137864365-1"
  customCSS = []
  RSSLink = ""

#  twitterName = "faketryghost"
#  fbName = "fakeghost"
  githubName = "meetupapp"
#  linkedinName = "eueung"
#  mediumName = ""

#  logo = "img/about.png"
  orgName = "meetup app"
  orgWebsite = "http://meetupapp.io"
  orgDescription = "Following the trend"

  showSupport = true

#  author = "Haruka Sao"
#  authorAvatar = "img/ghost-icon.png"
  # authorLocation = "Bandung, ID"
#  authorWebsite = "http://h-sao.com"
#  authorDescription = "Your description here"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Tokyo"
  url = "/categories/tokyo/"
  weight = 110

[[menu.main]]
  name = "Osaka"
  url = "/categories/osaka/"
  weight = 100

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 99

[[menu.main]]
  name = "告知サイト(External)"
  url = "https://meetupapp.connpass.com"
  weight = 95


